[workspace]
resolver = "3"
members = ["crates/core", "crates/core_derive", "crates/tui", "crates/gui"]

[workspace.package]
version = "0.1.0"
edition = "2024"
description = "An offline publication manager"
authors = ["The Spanish Inquisition"]
exclude = ["./images/*"]
readme = "Readme.md"
repository = "https://github.com/SpanishInquisition49/Minas-Tirith"
keywords = ["TUI", "GUI", "books"]

[workspace.dependencies]
color-eyre = "0.6.5"
tokio = { version = "1.52.3", features = ["full"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
chrono = { version = "0.4.45", features = ["serde"] }
tracing = "0.1.44"
tracing-appender = "0.2.5"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
sqlx = { version = "0.9.0", features = [
  "chrono",
  "json",
  "macros",
  "runtime-tokio",
  "sqlite",
] }
reqwest = { version = "0.13.4", features = ["json", "query"] }
slug = "0.1.6"
human_name = "2.0.4"
async-trait = "0.1.89"
trait-variant = "0.1.2"
directories = "6.0.0"
figment = { version = "0.10.19", features = ["env", "toml"] }
uuid = { version = "1.24.0", features = ["serde", "v4"] }
iroh = "1.0.2"
iroh-blobs = { version = "0.103.0", features = ["fs-store"] }
iroh-docs = "0.101.0"
iroh-gossip = "0.101.0"
iroh-mdns-address-lookup = "0.4.0"
epub = "2.1.5"
futures = "0.3.32"
n0-future = "0.3.2"
